// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: 'auth/login',
    uri: Uri.parse('auth/login'),
    routeBuilder: b0Builder,
  ),
];

const routePaths = (path: '/', auth: (path: '/auth', login: '/auth/login'));
